### ISSUE TITLE
error: there should be no gaps

### ISSUE THREAD

**Issue by duleise** [tdhock/PeakSegDisk#11]
hi
I tried to use `PeakSegFPOP_df` on the example ChIP data. I do not understand the error message below. What does the gap mean? I may have not fully understood all the words in the vignettes. Could you help me on this?
Thanks. 

```
library(PeakSegDisk)
data(ChIPreads, package="PeakSegDisk", envir=environment())
PeakSegDisk::PeakSegFPOP_df(subset(ChIPreads, experiment == "H3K36me3")[, -1], 10.5)
```
Error in PeakSegFPOP_file(prob.cov.bedGraph, penalty.str, db.file) : 
  there should be no gaps (columns 2-3) in input data file /private/var/folders/qg/bqnfm3s51ybdgnjq2br183zrxxfynt/T/RtmpwqaOFV/chr9-111387372-112271278/coverage.bedGraph
Timing stopped at: 0.008 0 0.002

**Comment by tdhock** [comment]
hi @duleise sorry for the delay. The error message means that there are some missing data, i.e. some bases have no data, between the first and the last base defined in the data.

it does not make sense to pass the entire set of aligned reads - you need to convert those data into a coverage profile (count of aligned reads at each base).
